# Get All
GET http://localhost:3000/jugadores HTTP/1.1
Content-Type: application/json
Accept: */*
###
# Get One
@name = testing
GET http://localhost:3000/jugadores/{{name}} HTTP/1.1
Content-Type: application/json
Accept: */*
###
# Create
POST http://localhost:3000/jugadores HTTP/1.1
Content-Type: application/json
Accept: */*

{
  "jugador":{
    "nombre_usuario": "testing",
    "nombre": "testing",
    "apellido": "testing",
    "contrasena": 123456
  }
}
###
# Update
PUT http://localhost:3000/jugadores/testing HTTP/1.1
Content-Type: application/json
Accept: */*

{
  "jugador":{
    "nombre_usuario": "changed",
    "nombre": "changed",
    "apellido": "changed",
    "contrasena": 123123
  }
}
###
# Delete
DELETE http://localhost:3000/jugadores/test HTTP/1.1
Content-Type: application/json
Accept: */*
###
# Attach
POST http://localhost:3000/jugadores/changed/pais HTTP/1.1
Content-Type: application/json
Accept: */*

{
  "nombre": "Argentina"
}
###
# Dettach
DELETE http://localhost:3000/jugadores/changed/pais HTTP/1.1
Content-Type: application/json
Accept: */*
###
# Get One Test
@name = testing
GET http://localhost:3000/jugadores/{{name}} HTTP/1.1

{{
  const { expect, assert } = require('chai');
  test('status code 200', () => {
    assert.equal(response.statusCode, 200)
  });

  test('has username', () => {
    assert.include(JSON.parse(response.body), {nombre_usuario: "testing"})
  })
}}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 131
etag: W/"83-oVEt8qQplw5rRi7LXECGpDnY9IQ"
date: Wed, 02 Nov 2022 05:16:01 GMT
connection: close
###
