GET http://localhost:3000/countries HTTP/1.1
Content-Type: application/json
Accept: */*
###
GET http://localhost:3000/countries/Argentina HTTP/1.1
Content-Type: application/json
Accept: */*
###
POST http://localhost:3000/countries HTTP/1.1
Content-Type: application/json
Accept: */*

{
  "pais":{
    "nombre": "Argentina"
  }
}
###
DELETE http://localhost:3000/players/Argentina HTTP/1.1
Content-Type: application/json
Accept: */*

HTTP/1.1 204  - No Content
x-powered-by: Express
access-control-allow-origin: *
date: Wed, 02 Nov 2022 19:12:40 GMT
connection: close